### ISSUE TITLE
After compiling under windwos, how to package the generated file into an exe file

### ISSUE THREAD

**Issue by yiwen9488** [ONLYOFFICE/build_tools#818] opened 2024-05-25 01:10 UTC
I tried to execute make exe with document-server-package library, but there seems to be some missing environment, can you give me some solutions?

**Comment by igwyd** [comment] 2024-05-27 06:18
Hello @yiwen9488, 
Duplicate of #819

**Closed** 2024-05-27 14:58 UTC
Labels: duplicate
