### ISSUE TITLE
Build server 8.2.0 using DOCKER failed

### ISSUE THREAD

**Issue by Inso2008** [ONLYOFFICE/build_tools#879] opened 2024-10-18 15:20 UTC
# Describe your problem:
Build OnlyOffice 8.2.0 according to the instructions on https://github.com/ONLYOFFICE/build_tools using DOCKER ends up with an error. 

```
In file included from ../../src/builtins/accessors.h:9:
../../src/base/bit-field.h:43:22: error: constexpr variable 'kMax' must be initialized by a constant expression
   43 |   static constexpr T kMax = static_cast<T>(kNumValues - 1);
      |                      ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../src/wasm/wasm-code-manager.h:344:30: note: in instantiation of template class 'v8::base::BitField<v8::internal::wasm::WasmCode::Kind, 0, 3, unsigned char>' requested here
  344 |   using ExecutionTierField = KindField::Next<ExecutionTier, 2>;
      |                              ^
../../src/base/bit-field.h:43:29: note: integer value 7 is outside the valid range of values [0, 3] for the enumeration type 'Kind'
   43 |   static constexpr T kMax = static_cast<T>(kNumValues - 1);
      |                             ^
1 error generated.
ninja: build stopped: subcommand failed.
[git] update: desktop-sdk
[git] update: core
[git] update: document-server-integration
[git] update: sdkjs
[git] update: document-templates
[git] update: sdkjs-forms
[git] update: core-fonts
[git] update: server
[git] update: dictionaries
[git] update: onlyoffice.github.io
[git] update: web-apps
[git] update: desktop-apps
[fetch & build]: boost
delete warning [file not exist]: ./boost.data
[fetch & build]: cef
delete warning [file not exist]: ./cef_binary.7z.data
[fetch & build]: icu
[fetch & build]: openssl
delete warning [file not exist]: ./openssl.data
gn gen out.gn/linux_64 --args="v8_static_library=true is_component_build=false v8_monolithic=true v8_use_external_startup_data=false use_custom_libcxx=false treat_warnings_as_errors=false target_cpu=\"x64\" v8_target_cpu=\"x64\" is_debug=false is_clang=true use_sysroot=false"
Error (ninja): 1
install dependencies...
Node.js version cannot be less 16
Reinstall
install qt...
---------------------------------------------
build branch:
---------------------------------------------
---------------------------------------------
build modules: desktop builder server
---------------------------------------------
Error (./make.py): 1
```

**build_tools base repo version**: 8.2.0.144

**Operating system**:  Ubuntu 22.04.5 LTS

**Comment by igwyd** [comment] 2024-10-30 12:32
Hello, sorry for the late reply, provide please the steps to reproduce the issue and the stand specification, cpu ram swap, often similar issues occur due to low RAM or swap. We recommend at least 4cpu 8ram and 4-8swap.

**Comment by Inso2008** [comment] 2024-11-04 16:19
I adjusted the server configuration to (4CPU, 8GB RAM, 8GB SWAP) and compiled the version with tag v8.2.0.147 and the build was successful. Thanks for your assistance.

**Comment by Rita-Bubnova** [comment] 2024-11-05 07:05
I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-11-05 07:05 UTC
