### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by Ccaomei** [ONLYOFFICE/build_tools#636] opened 2023-03-09 09:45 UTC
Hello, there is an error running./automate.py server on aarch64 platform. The specific error information is as follows:
FAILED: obj/third_party/zlib/zlib/deflate.o 
../../third_party/llvm-build/Release+Asserts/bin/clang -MMD -MF obj/third_party/zlib/zlib/deflate.o.d -DCPU_NO_SIMD -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DUSE_X11=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -DCR_CLANG_REVISION=\"llvmorg-12-init-16296-g5e476061-1\" -DCR_SYSROOT_HASH=ff4e6495cf3db79fc54addcb340f6f951885e4c1 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DZLIB_IMPLEMENTATION -I../.. -Igen -I../../third_party/zlib -fno-delete-null-pointer-checks -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -mfpu=neon -mfloat-abi=softfp --target=aarch64-linux-gnu -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -ftrivial-auto-var-init=pattern -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wall -Wno-unused-variable -Wno-misleading-indentation -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-psabi -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -Wno-max-tokens -O3 -fno-ident -fdata-sections -ffunction-sections -std=c11 --sysroot=../../build/linux/debian_sid_arm64-sysroot -Wno-implicit-fallthrough -c ../../third_party/zlib/deflate.c -o obj/third_party/zlib/zlib/deflate.o
clang: warning: argument unused during compilation: '-mfpu=neon' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mfloat-abi=softfp' [-Wunused-command-line-argument]
In file included from ../../third_party/zlib/deflate.c:57:
In file included from ../../third_party/zlib/contrib/optimizations/slide_hash_neon.h:9:
/core/Common/3dParty/v8_89/v8/build/linux/debian_sid_arm64-sysroot/usr/lib/gcc/aarch64-linux-gnu/7/include/arm_neon.h:38:9: error: unknown type name '__Int8x8_t'
typedef __Int8x8_t int8x8_t;
        ^
/core/Common/3dParty/v8_89/v8/build/linux/debian_sid_arm64-sysroot/usr/lib/gcc/aarch64-linux-gnu/7/include/arm_neon.h:39:9: error: unknown type name '__Int16x4_t'
typedef __Int16x4_t int16x4_t;
        ^
/core/Common/3dParty/v8_89/v8/build/linux/debian_sid_arm64-sysroot/usr/lib/gcc/aarch64-linux-gnu/7/include/arm_neon.h:40:9: error: unknown type name '__Int32x2_t'; did you mean '__int32_t'?
typedef __Int32x2_t int32x2_t;
        ^
/core/Common/3dParty/v8_89/v8/build/linux/debian_sid_arm64-sysroot/usr/include/aarch64-linux-gnu/bits/types.h:41:20: note: '__int32_t' declared here
typedef signed int __int32_t;
                   ^
In file included from ../../third_party/zlib/deflate.c:57:
In file included from ../../third_party/zlib/contrib/optimizations/slide_hash_neon.h:9:
/core/Common/3dParty/v8_89/v8/build/linux/debian_sid_arm64-sysroot/usr/lib/gcc/aarch64-linux-gnu/7/include/arm_neon.h:41:9: error: unknown type name '__Int64x1_t'; did you mean '__int64_t'?
typedef __Int64x1_t int64x1_t;
        ^
/core/Common/3dParty/v8_89/v8/build/linux/debian_sid_arm64-sysroot/usr/include/aarch64-linux-gnu/bits/types.h:44:25: note: '__int64_t' declared here
typedef signed long int __int64_t;
                        ^
In file included from ../../third_party/zlib/deflate.c:57:
In file included from ../../third_party/zlib/contrib/optimizations/slide_hash_neon.h:9:
/core/Common/3dParty/v8_89/v8/build/linux/debian_sid_arm64-sysroot/usr/lib/gcc/aarch64-linux-gnu/7/include/arm_neon.h:42:9: error: unknown type name '__Float16x4_t'
typedef __Float16x4_t float16x4_t;
        ^
/core/Common/3dParty/v8_89/v8/build/linux/debian_sid_arm64-sysroot/usr/lib/gcc/aarch64-linux-gnu/7/include/arm_neon.h:43:9: error: unknown type name '__Float32x2_t'
typedef __Float32x2_t float32x2_t;
        ^
/core/Common/3dParty/v8_89/v8/build/linux/debian_sid_arm64-sysroot/usr/lib/gcc/aarch64-linux-gnu/7/include/arm_neon.h:44:9: error: unknown type name '__Poly8x8_t'
typedef __Poly8x8_t poly8x8_t;
        ^
/core/Common/3dParty/v8_89/v8/build/linux/debian_sid_arm64-sysroot/usr/lib/gcc/aarch64-linux-gnu/7/include/arm_neon.h:45:9: error: unknown type name '__Poly16x4_t'
typedef __Poly16x4_t poly16x4_t;
        ^
/core/Common/3dParty/v8_89/v8/build/linux/debian_sid_arm64-sysroot/usr/lib/gcc/aarch64-linux-gnu/7/include/arm_neon.h:46:9: error: unknown type name '__Uint8x8_t'
typedef __Uint8x8_t uint8x8_t;
        ^
/core/Common/3dParty/v8_89/v8/build/linux/debian_sid_arm64-sysroot/usr/lib/gcc/aarch64-linux-gnu/7/include/arm_neon.h:47:9: error: unknown type name '__Uint16x4_t'
typedef __Uint16x4_t uint16x4_t;
        ^
/core/Common/3dParty/v8_89/v8/build/linux/debian_sid_arm64-sysroot/usr/lib/gcc/aarch64-linux-gnu/7/include/arm_neon.h:48:9: error: unknown type name '__Uint32x2_t'
typedef __Uint32x2_t uint32x2_t;
        ^
/core/Common/3dParty/v8_89/v8/build/linux/debian_sid_arm64-sysroot/usr/lib/gcc/aarch64-linux-gnu/7/include/arm_neon.h:49:9: error: unknown type name '__Float64x1_t'
typedef __Float64x1_t float64x1_t;
        ^
/core/Common/3dParty/v8_89/v8/build/linux/debian_sid_arm64-sysroot/usr/lib/gcc/aarch64-linux-gnu/7/include/arm_neon.h:50:9: error: unknown type name '__Uint64x1_t'
typedef __Uint64x1_t uint64x1_t;
        ^
/core/Common/3dParty/v8_89/v8/build/linux/debian_sid_arm64-sysroot/usr/lib/gcc/aarch64-linux-gnu/7/include/arm_neon.h:51:9: error: unknown type name '__Int8x16_t'; did you mean '__int16_t'?
typedef __Int8x16_t int8x16_t;
        ^
/core/Common/3dParty/v8_89/v8/build/linux/debian_sid_arm64-sysroot/usr/include/aarch64-linux-gnu/bits/types.h:39:26: note: '__int16_t' declared here
typedef signed short int __int16_t;
                         ^
In file included from ../../third_party/zlib/deflate.c:57:
In file included from ../../third_party/zlib/contrib/optimizations/slide_hash_neon.h:9:
/core/Common/3dParty/v8_89/v8/build/linux/debian_sid_arm64-sysroot/usr/lib/gcc/aarch64-linux-gnu/7/include/arm_neon.h:52:9: error: unknown type name '__Int16x8_t'
typedef __Int16x8_t int16x8_t;
        ^
/core/Common/3dParty/v8_89/v8/build/linux/debian_sid_arm64-sysroot/usr/lib/gcc/aarch64-linux-gnu/7/include/arm_neon.h:53:9: error: unknown type name '__Int32x4_t'; did you mean '__int32_t'?
typedef __Int32x4_t int32x4_t;
        ^
/core/Common/3dParty/v8_89/v8/build/linux/debian_sid_arm64-sysroot/usr/include/aarch64-linux-gnu/bits/types.h:41:20: note: '__int32_t' declared here
typedef signed int __int32_t;
                   ^
In file included from ../../third_party/zlib/deflate.c:57:
In file included from ../../third_party/zlib/contrib/optimizations/slide_hash_neon.h:9:
/core/Common/3dParty/v8_89/v8/build/linux/debian_sid_arm64-sysroot/usr/lib/gcc/aarch64-linux-gnu/7/include/arm_neon.h:54:9: error: unknown type name '__Int64x2_t'; did you mean '__int64_t'?
typedef __Int64x2_t int64x2_t;
        ^
/core/Common/3dParty/v8_89/v8/build/linux/debian_sid_arm64-sysroot/usr/include/aarch64-linux-gnu/bits/types.h:44:25: note: '__int64_t' declared here
typedef signed long int __int64_t;
                        ^
In file included from ../../third_party/zlib/deflate.c:57:
In file included from ../../third_party/zlib/contrib/optimizations/slide_hash_neon.h:9:
/core/Common/3dParty/v8_89/v8/build/linux/debian_sid_arm64-sysroot/usr/lib/gcc/aarch64-linux-gnu/7/include/arm_neon.h:55:9: error: unknown type name '__Float16x8_t'; did you mean '__SVFloat16_t'?
typedef __Float16x8_t float16x8_t;
        ^
note: '__SVFloat16_t' declared here
/core/Common/3dParty/v8_89/v8/build/linux/debian_sid_arm64-sysroot/usr/lib/gcc/aarch64-linux-gnu/7/include/arm_neon.h:56:9: error: unknown type name '__Float32x4_t'
typedef __Float32x4_t float32x4_t;
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

**Comment by igwyd** [comment] 2023-11-07 08:16
Hello @Ccaomei, sorry for the late reply.
Duplicate of #470

**Closed** 2023-11-07 08:33 UTC
Labels: duplicate
