### ISSUE TITLE
Development mode ran incorrectly

### ISSUE THREAD

**Issue by yiwen9488** [ONLYOFFICE/build_tools#825] opened 2024-06-19 01:44 UTC
cd build_tools/develop
docker pull onlyoffice/documentserver
docker build -t documentserver-develop .

or run with `sdkjs`, `web-apps` and `server`

```bash
docker run -i -t -p 80:80 --restart=always -e ALLOW_PRIVATE_IP_ADDRESS=true -v $pwd/sdkjs:/var/www/onlyoffice/documentserver/sdkjs -v $pwd/web-apps:/var/www/onlyoffice/documentserver/web-apps -v $pwd/server:/var/www/onlyoffice/documentserver/server documentserver-develop

logs:
2024-06-19 09:40:08 ==> /var/log/onlyoffice/documentserver/converter/err.log <==
2024-06-19 09:40:08 /var/www/onlyoffice/documentserver/server/Common/node_modules/config/lib/config.js:203
2024-06-19 09:40:08     throw new Error('Configuration property "' + property + '" is not defined');
2024-06-19 09:40:08     ^
2024-06-19 09:40:08 
2024-06-19 09:40:08 Error: Configuration property "tenants.baseDomain" is not defined
2024-06-19 09:40:08     at Config.get (/var/www/onlyoffice/documentserver/server/Common/node_modules/config/lib/config.js:203:11)
2024-06-19 09:40:08     at Object.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/sources/tenantManager.js:45:37)
2024-06-19 09:40:08     at Module._compile (node:internal/modules/cjs/loader:1364:14)
2024-06-19 09:40:08     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
2024-06-19 09:40:08     at Module.load (node:internal/modules/cjs/loader:1203:32)
2024-06-19 09:40:08     at Module._load (node:internal/modules/cjs/loader:1019:12)
2024-06-19 09:40:08     at Module.require (node:internal/modules/cjs/loader:1231:19)
2024-06-19 09:40:08     at require (node:internal/modules/helpers:177:18)
2024-06-19 09:40:08     at Object.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/sources/operationContext.js:38:23)
2024-06-19 09:40:08     at Module._compile (node:internal/modules/cjs/loader:1364:14)
2024-06-19 09:40:08 
2024-06-19 09:40:08 Node.js v18.20.3
2024-06-19 09:40:14 /var/www/onlyoffice/documentserver/server/Common/node_modules/config/lib/config.js:203
2024-06-19 09:40:14     throw new Error('Configuration property "' + property + '" is not defined');
2024-06-19 09:40:14     ^
2024-06-19 09:40:14 
2024-06-19 09:40:14 Error: Configuration property "tenants.baseDomain" is not defined
2024-06-19 09:40:14     at Config.get (/var/www/onlyoffice/documentserver/server/Common/node_modules/config/lib/config.js:203:11)
2024-06-19 09:40:14     at Object.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/sources/tenantManager.js:45:37)
2024-06-19 09:40:14     at Module._compile (node:internal/modules/cjs/loader:1364:14)
2024-06-19 09:40:14     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
2024-06-19 09:40:14     at Module.load (node:internal/modules/cjs/loader:1203:32)
2024-06-19 09:40:14     at Module._load (node:internal/modules/cjs/loader:1019:12)
2024-06-19 09:40:14     at Module.require (node:internal/modules/cjs/loader:1231:19)
2024-06-19 09:40:14     at require (node:internal/modules/helpers:177:18)
2024-06-19 09:40:14     at Object.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/sources/operationContext.js:38:23)
2024-06-19 09:40:14     at Module._compile (node:internal/modules/cjs/loader:1364:14)
2024-06-19 09:40:14 
2024-06-19 09:40:14 Node.js v18.20.3
![QQ图片20240619094140](https://github.com/ONLYOFFICE/build_tools/assets/31262596/29556809-8a38-4b56-9bd4-da0cc77a857d)

**Comment by yiwen9488** [comment] 2024-06-27 01:18
> Hello @yiwen9488 i checked your scenario and got no errors, documentserver started with sdkjs, web-apps and server. Did you run it before 8.1.0? Try running again.

I have updated the latest version of the image and the problem still exists
The code module is also updated to the latest master
![Snipaste_2024-06-27_09-14-54](https://github.com/ONLYOFFICE/build_tools/assets/31262596/5064d90f-c26b-4c73-94bd-43354f75f764)


docker pull onlyoffice/documentserver

**Comment by igwyd** [comment] 2024-07-01 05:25
Then we need additional information about your stand: OS, docker version, it's updated server?

**Comment by yiwen9488** [comment] 2024-07-02 00:40
版本	Windows 11 专业版
版本	23H2
安装日期	‎2023/‎11/‎3
操作系统版本	22631.3296
体验	Windows Feature Experience Pack 1000.22687.1000.0

Client:
 Version:           26.1.4
 API version:       1.45
 Go version:        go1.21.11
 Git commit:        5650f9b
 Built:             Wed Jun  5 11:29:54 2024
 OS/Arch:           windows/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.31.1 (153621)
 Engine:
  Version:          26.1.4
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       de5c9cf
  Built:            Wed Jun  5 11:29:22 2024
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.6.33
  GitCommit:        d2d58213f83a351ca8f528a95fbd145f5654e957
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

onlyoffice/documentserver

**Comment by igwyd** [comment] 2024-07-03 15:51
Probably you didn't go to the repositories folder `cd ../..`, I had a similar error. Created ticket #68985. Try running it like this:
```
git clone https://github.com/ONLYOFFICE/build_tools.git
cd build_tools/develop
docker pull onlyoffice/documentserver
docker build --no-cache -t documentserver-develop .
git clone https://github.com/ONLYOFFICE/sdkjs.git
git clone https://github.com/ONLYOFFICE/web-apps.git
git clone https://github.com/ONLYOFFICE/server.git
docker run -i -t -p 80:80 --restart=always -e ALLOW_PRIVATE_IP_ADDRESS=true -v $pwd/sdkjs:/var/www/onlyoffice/documentserver/sdkjs -v $pwd/web-apps:/var/www/onlyoffice/documentserver/web-apps -v $pwd/server:/var/www/onlyoffice/documentserver/server documentserver-develop
```

**Comment by yiwen9488** [comment] 2024-07-04 00:40
> 可能你没有去存储库文件夹，我有类似的错误。已创建工单 #68985。尝试像这样运行它：`cd ../..`
> 
> ```
> git clone https://github.com/ONLYOFFICE/build_tools.git
> cd build_tools/develop
> docker pull onlyoffice/documentserver
> docker build --no-cache -t documentserver-develop .
> git clone https://github.com/ONLYOFFICE/sdkjs.git
> git clone https://github.com/ONLYOFFICE/web-apps.git
> git clone https://github.com/ONLYOFFICE/server.git
> docker run -i -t -p 80:80 --restart=always -e ALLOW_PRIVATE_IP_ADDRESS=true -v $pwd/sdkjs:/var/www/onlyoffice/documentserver/sdkjs -v $pwd/web-apps:/var/www/onlyoffice/documentserver/web-apps -v $pwd/server:/var/www/onlyoffice/documentserver/server documentserver-develop
> ```


git clone https://github.com/ONLYOFFICE/build_tools.git
cd build_tools/develop
docker pull onlyoffice/documentserver
docker build --no-cache -t documentserver-develop .
cd ../..
git clone https://github.com/ONLYOFFICE/sdkjs.git
git clone https://github.com/ONLYOFFICE/web-apps.git
git clone https://github.com/ONLYOFFICE/server.git
docker run -i -t -p 80:80 --restart=always -e ALLOW_PRIVATE_IP_ADDRESS=true -v $pwd/sdkjs:/var/www/onlyoffice/documentserver/sdkjs -v $pwd/web-apps:/var/www/onlyoffice/documentserver/web-apps -v $pwd/server:/var/www/onlyoffice/documentserver/server documentserver-develop


build_tools,sdkjs,web-apps,server 
 The directory is the same level. I'm sure of that

**Comment by igwyd** [comment] 2024-07-04 05:13
Then I have only one assumption that some repositories were not downloaded to the end, because i tested on the same stand as you.

**Comment by BeginnerCong** [comment] 2024-07-05 02:33
![image](https://github.com/ONLYOFFICE/build_tools/assets/42209180/635a790a-dfba-4978-8aac-c3fe7f5ed404)
I am encountering the same problem，The command docker run -i -t -p 8003:80 --restart=always -e ALLOW_PRIVATE_IP_ADDRESS=true -e JWT_ENABLED=false -v /mnt/d/onlyoffice_dev/sdkjs:/var/www/onlyoffice/documentserver/sdkjs -v /mnt/d/onlyoffice_dev/web-apps:/var/www/onlyoffice/documentserver/web-apps --name my_onlyoffice documentserver-develop works fine，But when I run docker run -i -t -p 8004:80 --restart=always -e ALLOW_PRIVATE_IP_ADDRESS=true -e JWT_ENABLED=false -v /mnt/d/onlyoffice_dev/sdkjs:/var/www/onlyoffice/documentserver/sdkjs -v /mnt/d/onlyoffice_dev/web-apps:/var/www/onlyoffice/documentserver/web-apps -v /mnt/d/onlyoffice_dev/server:/var/www/onlyoffice/documentserver/server --name my_onlyoffice_server documentserver-develop, I encounter the same problem.

**Comment by yiwen9488** [comment] 2024-07-05 02:40
> ![image](https://private-user-images.githubusercontent.com/42209180/345983656-635a790a-dfba-4978-8aac-c3fe7f5ed404.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNDc0NTgsIm5iZiI6MTcyMDE0NzE1OCwicGF0aCI6Ii80MjIwOTE4MC8zNDU5ODM2NTYtNjM1YTc5MGEtZGZiYS00OTc4LThhYWMtYzNmZTdmNWVkNDA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDAyMzkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxZmVhZTQwZjBiZjJiN2YxZDA5ZGNiYjQzOWQ4MmZiY2Q5ODI3MjBlYThiMTViYzM4OTJmZWI3NjE5Nzc4NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tAKUyfRgIC0T2q7ur1fqXzOCzi1ZNvr_TKmSdfvKSxY) I am encountering the same problem，The command docker run -i -t -p 8003:80 --restart=always -e ALLOW_PRIVATE_IP_ADDRESS=true -e JWT_ENABLED=false -v /mnt/d/onlyoffice_dev/sdkjs:/var/www/onlyoffice/documentserver/sdkjs -v /mnt/d/onlyoffice_dev/web-apps:/var/www/onlyoffice/documentserver/web-apps --name my_onlyoffice documentserver-develop works fine，But when I run docker run -i -t -p 8004:80 --restart=always -e ALLOW_PRIVATE_IP_ADDRESS=true -e JWT_ENABLED=false -v /mnt/d/onlyoffice_dev/sdkjs:/var/www/onlyoffice/documentserver/sdkjs -v /mnt/d/onlyoffice_dev/web-apps:/var/www/onlyoffice/documentserver/web-apps -v /mnt/d/onlyoffice_dev/server:/var/www/onlyoffice/documentserver/server --name my_onlyoffice_server documentserver-develop, I encounter the same problem.

That's my problem, too. It doesn't matter how I try. It's the same problem, you know

**Comment by igwyd** [comment] 2024-07-08 07:12
@BeginnerCong @yiwen9488 we think this is a problem with downloading packages, can you send the output from the console comand ```docker run```?

**Comment by BeginnerCong** [comment] 2024-07-11 07:03
@yiwen9488 
run with sdkjs and web-apps,This is a screenshot of the normal startup,The version that is constructed successfully is 7.5.1. Build: 23
![image](https://github.com/ONLYOFFICE/build_tools/assets/42209180/66bcd01e-00dc-4e2a-a31c-4f825fded181)
run with sdkjs, web-apps and server,This is a screenshot of the abnormal startup，Look at the part I circled, is this part of the script missing?
![image](https://github.com/ONLYOFFICE/build_tools/assets/42209180/8c9f8ad7-e568-4c2e-9c6c-0ffcf715249e)

**Comment by igwyd** [comment] 2024-07-11 15:32
@BeginnerCong This is not a bug but a launch feature. Themes are generated elsewhere because it is launched with an external ```server```. The error is most likely earlier in the log. Can you attach whole log file?

**Comment by BeginnerCong** [comment] 2024-07-12 08:18
[log.txt](https://github.com/user-attachments/files/16190745/log.txt)
This is a complete output log file of the startup process.

**Comment by igwyd** [comment] 2024-07-16 10:21
The log shows that the docker is from the old version, try to delete all repositories and docker image and run all commands again. Be sure to check that the repositories are updated and they are from master branch. Create a docker image again:
```
docker pull onlyoffice/documentserver
docker build --no-cache -t documentserver-develop .
```

**Comment by BeginnerCong** [comment] 2024-07-17 04:45
@igwyd Thank you very much, you solved my problem. But which part of the log did you see that Docker is from an old version？

**Comment by igwyd** [comment] 2024-09-09 07:37
We close this issue beacause the problem is solved. Regarding docker, the developer noticed that some messages were missing in the old version.

**Closed** 2024-09-09 07:40 UTC
Labels: question
