### ISSUE TITLE
Cannot compile source code to generate file on arm64 architecture

### ISSUE THREAD

**Issue by yiwen9488** [ONLYOFFICE/build_tools#680] opened 2023-05-23 07:34 UTC
**Describe your problem**:

**Steps to reproduce the problem**:

cd /build_tools/tools/linux/
./automate.py server

Wait for some time before an error occurs

---------------------------------------------
build modules: server
---------------------------------------------
[fetch & build]: boost
[fetch & build]: cef
[fetch & build]: icu
[fetch & build]: openssl
gn gen out.gn/linux_arm64 --args="v8_static_library=true is_component_build=false v8_monolithic=true v8_use_external_startup_data=false use_custom_libcxx=false treat_warnings_as_errors=false target_cpu=\"arm64\" v8_target_cpu=\"arm64\" use_sysroot=false v8_static_library=true is_component_build=false v8_use_snapshot=false clang_base_path="/usr/" treat_warnings_as_errors=false clang_use_chrome_plugins=false fatal_linker_warnings=false is_debug=false"
Traceback (most recent call last):
  File "/opt/build_tools/scripts/../../core/Common/3dParty/v8_89/depot_tools/gn.py", line 74, in <module>
    sys.exit(main(sys.argv))
  File "/opt/build_tools/scripts/../../core/Common/3dParty/v8_89/depot_tools/gn.py", line 69, in main
    return subprocess.call([gn_path] + args[1:])
  File "/usr/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/opt/core/Common/3dParty/v8_89/v8/buildtools/linux64/gn'
Error (gn): 1
Error (./make.py): 1
**build_tools base repo version**:
  Latest
**Operating system**:
 ubuntu:18.04 aarch64
**Compiler version**:
  Latest

**Comment by igwyd** [comment] 2023-11-07 08:16
Hello @yiwen9488, sorry for the late reply.
Duplicate of #470

**Closed** 2023-11-07 08:33 UTC
Labels: duplicate
