### ISSUE TITLE
Something wrong when Building Document Server source code

### ISSUE THREAD

**Issue by smartbi** [ONLYOFFICE/build_tools#104] opened 2020-05-30 11:50 UTC
I try to Building Document Server source code 
https://helpcenter.onlyoffice.com/server/linux/document/compile-source-code.aspx

But when compile v8, somethings failed.

../../src/objects-body-descriptors.h:101:22: note: candidate: ‘template<int start_offset, int end_offset, int size> template<class StaticVisitor> static void v8::internal::FixedBodyDescriptor<start_offset, end_offset, size>::IterateBody(v8::internal::HeapObject*, int)’
  101 |   static inline void IterateBody(HeapObject* obj, int object_size) {
      |                      ^~~~~~~~~~~
../../src/objects-body-descriptors.h:101:22: note:   template argument deduction/substitution failed:
../../src/objects-body-descriptors.h:102:20: note:   candidate expects 2 arguments, 1 provided
  102 |     IterateBody(obj);
      |                    ^
cc1plus: all warnings being treated as errors
[19/1493] CXX obj/v8_libbase/stack_trace.o
ninja: build stopped: subcommand failed.
Error (ninja): 1
Error (./make.py): 1

How can I fix it ?

I build it in

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal

**Comment by ShockwaveNN** [comment] 2020-05-30 19:28
This will not work on ubuntu 20.04 because we use not so recent v8
Try to use Ubuntu 14.04 or provided Dockerfile at root of repo

**Comment by smartbi** [comment] 2020-06-05 02:12
I try to build in 14.04.

Another error:
Cannot open file /DocumentServer/build_tools/videoplayer/videoplayer.pro

I exec ls in this directory, it is an empty directory. no files in it

**Comment by ShockwaveNN** [comment] 2020-06-05 07:09
Possible duplicate of https://github.com/ONLYOFFICE/build_tools/issues/82

**Comment by smartbi** [comment] 2020-06-09 02:54
I build all successful, and running document server according to
 https://helpcenter.onlyoffice.com/server/linux/document/compile-source-code.aspx?utm_source=blog&utm_medium=social&utm_campaign=build_tools&_ga=2.193802990.275044894.1590651206-1775026576.1576834176#Running


After all three servers? How can I access it ?
When visit http://myserver/  , it response "Cannot GET /api.js"

**Comment by ShockwaveNN** [comment] 2020-06-09 06:14
>When visit http://myserver/ , it response "Cannot GET /api.js"

This is correct, you should connect to any DMS-system manually (like nextcloud, owncloud), or use some of test examples from https://github.com/ONLYOFFICE/document-server-integration

**Comment by ShockwaveNN** [comment] 2020-08-10 11:39
This issue was closed due to no response.

**Closed by ShockwaveNN** 2020-08-10 11:39 UTC
Labels: waiting feedback
