### ISSUE TITLE
Problems with building from tag

### ISSUE THREAD

**Issue by barnettZQG** [ONLYOFFICE/build_tools#78] opened 2020-04-18 13:21 UTC
logs:
```
9.9 -I../../include/QtWidgets/5.9.9/QtWidgets -I../../include/QtGui/5.9.9 -I../../include/QtGui/5.9.9/QtGui -I../../include/QtCore/5.9.9 -I../../include/QtCore/5.9.9/QtCore -I../../include/QtWidgets -I../../include/QtGui -I../../include/QtCore -I.moc -I../../mkspecs/linux-g++ -o .obj/qglfunctions.o qglfunctions.cpp
rm -f libQt5Test.so.5.9.9 libQt5Test.so libQt5Test.so.5 libQt5Test.so.5.9
make[5]: write error
make[4]: *** [sub-minimal-make_first] Error 1
make[4]: write error
make[3]: *** [sub-platforms-make_first] Error 1
make[3]: *** Waiting for unfinished jobs....
make[5]: write error
make[4]: *** [sub-generic-make_first] Error 1
make[4]: write error
make[3]: *** [sub-bearer-make_first] Error 1
make[5]: write error
make[4]: *** [sub-gtk3-make_first] Error 1
make[4]: write error
make[3]: *** [sub-platformthemes-make_first] Error 1
make[5]: write error
make[4]: *** [sub-ibus-make_first] Error 1
make[4]: *** Waiting for unfinished jobs....
make[5]: write error
make[4]: *** [sub-compose-make_first] Error 1
make[4]: write error
make[3]: *** [sub-platforminputcontexts-make_first] Error 1
make[3]: write error
make[2]: *** [sub-plugins-make_first] Error 1
make[2]: write error
make[1]: *** [sub-src-make_first] Error 1
make[1]: write error
make: *** [module-qtbase-make_first] Error 1
Error (make): 2
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='ANSI_X3.4-1968'>
BlockingIOError: [Errno 11] write could not complete without blocking
g++ -Wl,--no-undefined -Wl,--version-script,QtTest.version -Wl,-O1 -fuse-ld=gold -Wl,--enable-new-dtags -Wl,-z,origin -Wl,-rpath,\$ORIGIN -shared -Wl,-Bsymbolic-functions -Wl,-soname,libQt5Test.so.5 -o libQt5Test.so.5.9.9 .obj/qtestcase.o .obj/qtestlog.o .obj/qtesttable.o .obj/qtestdata.o .obj/qtestresult.o .obj/qasciikey.o .obj/qplaintestlogger.o .obj/qxmltestlogger.o .obj/qsignaldumper.o .obj/qabstracttestlogger.o .obj/qbenchmark.o .obj/qbenchmarkmeasurement.o .obj/qbenchmarkvalgrind.o .obj/qbenchmarkevent.o .obj/qbenchmarkperfevents.o .obj/qbenchmarkmetric.o .obj/qcsvbenchmarklogger.o .obj/qteamcitylogger.o .obj/qtestelement.o .obj/qtestelementattribute.o .obj/qtestmouse.o .obj/qtestxunitstreamer.o .obj/qxunittestlogger.o .obj/qtestblacklist.o .obj/moc_qtesteventloop.o  -L/build_tools/tools/linux/qt-everywhere-opensource-src-5.9.9/qtbase/lib -lQt5Core -lpthread
```

tag: v5.5.2.2
build cmd:
```
docker build --tag onlyoffice-document-editors-builder .
docker run -v $PWD/out:/build_tools/out onlyoffice-document-editors-builder
```
Hoping for help

**Comment by ShockwaveNN** [comment] 2020-04-20 09:12
Just checked on 

```
git checkout v5.5.2.2
docker build --tag onlyoffice-document-editors-builder .
docker run -v $PWD/out:/build_tools/out onlyoffice-document-editors-builder
```
and got no such error.

So please attach full build log and step-by step instruction how did you checkout specificed tag

Also please note that v5.5.2 is curently in development and may be not working at all

**Comment by barnettZQG** [comment] 2020-04-21 03:37
I will try building v5.5.1.85

**Comment by barnettZQG** [comment] 2020-04-21 05:20
build command:
```
python3 ./automate.py server
```
last error log:
```
make[1]: Leaving directory `/core/Test/Applications/StandardTester'
cd videoplayer/ && ( test -e Makefile || /build_tools/tools/linux/qt_build/Qt-5.9.9/gcc_64/bin/qmake -o Makefile /build_tools/videoplayer/videoplayer.pro -nocache 'CONFIG+=server ' ) && make -f Makefile
Cannot find file: /build_tools/videoplayer/videoplayer.pro.
make: *** [sub-videoplayer-make_first-ordered] Error 2
Error (make): 2
Error (./make.py): 1
```
maybe useful log:
![image](https://user-images.githubusercontent.com/18493394/79824183-2ffc8e80-83c8-11ea-9538-dbeb98962789.png)

**Comment by ShockwaveNN** [comment] 2020-04-21 07:44
@barnettZQG I'll try to build v5.5.1.85 version, but we strongly advise try to build only master branch, since all other branches or tags may be broken in current time (like error with videoplayer looks like I see was before)
So best advise - build master version (or release tag v5.5.1.76)
But I try to build v5.5.1.85 to check if I got same error

**Comment by ShockwaveNN** [comment] 2020-04-21 09:26
Yeah, I can confirm this error on v5.5.1.85

Figuring out the reason

**Comment by ShockwaveNN** [comment] 2020-04-21 10:52
We found a reason.

Currently on `master` of `build_tools` there is no way of building projects from tags, only from branchs

@K0R0L take a look and promise to implement ability to build from tag on `develop` branch of `build_tools` in several days

**Comment by ShockwaveNN** [comment] 2020-04-21 15:52
Yeah, seems this is a duplicate of #74, so I continue discussion about building from tag in that issue

**Closed by ShockwaveNN** 2020-04-21 15:52 UTC

**Comment by ShockwaveNN** [comment] 2020-04-21 18:43
@warnerbryce I've pinned down problem with videoplayer and create seprate issue at #82
