### ISSUE TITLE
Do a complete compilation on x86 AMD64, and then access  Cannot GET /

### ISSUE THREAD

**Issue by 1205469665** [ONLYOFFICE/build_tools#370] opened 2021-08-25 07:13 UTC
Hello, could you please ask,Do a complete compilation on x86 AMD64, and then access  
![image](https://user-images.githubusercontent.com/16591941/130743713-d9412ddc-af44-4c1a-a1d9-6dff16fc80ca.png)

 
Access 80 Why is that so is there something I'm not configuring?

**Comment by ShockwaveNN** [comment] 2021-08-25 07:15
This is correct behavior. Compiled DocumentServer do not include any frontend for storing files

You should setup it separate from this repo:
https://github.com/ONLYOFFICE/document-server-integration/

Better use nodejs example, since it's most feature reach

**Comment by 1205469665** [comment] 2021-08-25 08:12
您好,麻烦了,使用了java进行document-server-integration/ 访问
![image](https://user-images.githubusercontent.com/16591941/130752539-41321e29-9351-4ae6-8284-ae5ca8d71d69.png)
[2021-08-23T14:16:09.374] [ERROR] nodeJS - error downloadFile:url=http://172.16.30.7:8080/OnlineEditorsExampleJava_war_exploded/app_data/172.16.30.7/new%20%281%29.docx;attempt=3;code:null;connect:null;(id=-1663177208)
Error: Error response: statusCode:404 ;body:
<!doctype html><html lang="zh"><head><title>HTTP status 404 - Not found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP状态 404 - 未找到</h1><hr class="line" /><p><b>Type </b> Status report </p><p><b> Message </b> 
The requested resource [/OnlineEditorsExampleJava_war_exploded/app_data/172.16.30.7/new%20%281%29.docx] unavailable < / p > < p > < b > description < / b > 
The source server was unable to find the representation of the target resource or was unwilling to expose an existing representation of the resource.</p><hr class="line" /><h3>Apache Tomcat/7.0.107</h3></body></html>
    at Request._callback (/snapshot/server/build/server/Common/sources/utils.js:0:0)
    at Request.init.self.callback (/snapshot/server/build/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2021-08-23T14:16:10.375] [DEBUG] nodeJS - ExitCode (code=0;signal=null;error:-81;id=-1663177208)
[2021-08-23T14:16:10.376] [DEBUG] nodeJS - output (data={"cmd":{"withAuthorization":true,"c":"open","id":"-1663177208","userid":"uid-1","format":"docx","url":"http://172.16.30.7:8080/OnlineEditorsExampleJava_war_exploded/app_data/172.16.30.7/new%20%281%29.docx","title":"new (1).docx","outputformat":8192,"outputpath":"Editor.bin","embeddedfonts":false,"status_info":-81,"lcid":9,"nobase64":true}};id=-1663177208)
[2021-08-23T14:16:10.376] [DEBUG] nodeJS - postProcess (id=-1663177208)
[2021-08-23T14:16:10.376] [DEBUG] nodeJS - deleteFolderRecursive (id=-1663177208)
Hello, may I ask why this has been unable to visit, thank you

**Comment by ShockwaveNN** [comment] 2021-08-25 08:18
This error on screenshot mean that DocumentServer host cannot download file from run Java example

This may be firewall\network or any other reasons

Try to download file from DocumentServer host using wget and see for any error

But those are general advices - I'm not very good at Java

**Comment by 1205469665** [comment] 2021-08-25 08:35
I have already known the problem. I need to modify the URL method by myself. There seems to be some problems in the way of obtaining doc

**Comment by ShockwaveNN** [comment] 2021-08-25 08:40
If you make some docker-compose file to reproduce this problem - I think we can fix it or find why this happen

**Comment by 1205469665** [comment] 2021-08-25 11:01
This is an error in the Java demo of document-server-integration, which has nothing to do with onlyOffice Docker

**Comment by ShockwaveNN** [comment] 2021-08-25 11:07
I understand that, but there is a lot of configuration properties in Java example, so reliable test case will be to setup docker-compose of Java example and connect it to DocumentServer docker image

**Comment by ShockwaveNN** [comment] 2021-10-01 11:06
Closing this issue since it's not a problem with compilation per-se, but problem with setting up Java example

And also - no responce

**Closed by ShockwaveNN** 2021-10-01 11:06 UTC
