### ISSUE TITLE
Menu is not displayed

### ISSUE THREAD

**Issue by Revvz** [ONLYOFFICE/build_tools#406] opened 2021-11-18 12:16 UTC
**Describe your problem**:
Hello! I assembled the office by manual
https://helpcenter.onlyoffice.com/installation/docs-community-compile.aspx. But unfortunately, it is impossible to use it, since icons are not displayed in my menu. Attaching photo. What to do about it? Or is it a build bug?
Thanks.
![onlyoffice bug](https://user-images.githubusercontent.com/56865086/142413777-4849eef8-68c7-4654-af76-94c3b54780e2.jpg)

**Operating system**:
Ubuntu 14,04

**Comment by ShockwaveNN** [comment] 2022-02-14 07:47
Duplicate of https://github.com/ONLYOFFICE/build_tools/issues/409

**Closed by ShockwaveNN** 2022-02-14 07:47 UTC
