### ISSUE TITLE
cannot build : java.io.IOException: No space left on device

### ISSUE THREAD

**Issue by zhangft7478191** [ONLYOFFICE/build_tools#805] opened 2024-04-26 02:41 UTC
The./automate.py file cannot complete the construction work properly. I have executed it on Ubuntu 16.04 and 20.04 respectively, and the server is located in Virginia, USA. Could you please help me see what the problem is, or is it due to external reasons? Please confirm if you can build it normally. thanks!
```

  CXX(target) Release/obj.target/core/core.oecycle win-ca@3.5.0~postinstall: win-ca@3.5.0
added 237 packages in 2.537s
In file included from ../core.cc:2:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2298:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
 2298 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
In file included from ../core.cc:1:
../core.cc: At global scope:
/root/.cache/node-gyp/14.21.3/include/node/node.h:793:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  793 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/root/.cache/node-gyp/14.21.3/include/node/node.h:827:3: note: in expansion of macro ‘NODE_MODULE_X’
  827 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../core.cc:190:1: note: in expansion of macro ‘NODE_MODULE’
  190 | NODE_MODULE(core, Init);
      | ^~~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/core.nodege-q@4.0.0 extracted to /root/server/DocService/node_modules/image-q (106ms)
  COPY Release/core.nodextractTree: sill extract image-q@4.0.0 extracted to /root/server/DocService/node_modules/image-q (106ms)
make: Leaving directory '/root/server/Metrics/node_modules/modern-syslog/build'
added 11 packages in 3.569s

> oracledb@6.3.0 install /root/server/DocService/node_modules/oracledb
> node package/install.js

oracledb ********************************************************************************
oracledb ** Node-oracledb 6.3.0 installed in Node.js 14.21.3 (linux, x64)
oracledb ** To use node-oracledb in Thin mode, no additional steps are needed.
oracledb ** To use the optional Thick mode, the Oracle Client libraries (64-bit)
oracledb ** must be available, see the installation instructions:
oracledb **   https://node-oracledb.readthedocs.io/en/latest/user_guide/installation.html#node-oracledb-installation-on-linux
oracledb ********************************************************************************

added 463 packages in 3.91s
> pkg@5.8.1
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v16.16.0-linux-x64          [====================] 100%

> Warning Cannot resolve ''./' + config.get('services.CoAuthoring.server.editorDataStorage')'
  /root/server/DocService/sources/DocsCoServer.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve ''./' + config.get('storage.name')'
  /root/server/Common/sources/storage-base.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  %1: node_modules/open/xdg-open
  %2: path-to-executable/xdg-open
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  %1: node_modules/open/xdg-open
  %2: path-to-executable/xdg-open
> Warning Failed to make bytecode node16-x64 for file /snapshot/server/Common/node_modules/openpgp/dist/openpgp.js
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
> pkg@5.8.1
> Warning Cannot resolve ''./' + config.get('storage.name')'
  /root/server/Common/sources/storage-base.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve ''./' + config.get('services.CoAuthoring.server.editorDataStorage')'
  /root/server/DocService/sources/DocsCoServer.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  %1: ../DocService/node_modules/open/xdg-open
  %2: path-to-executable/xdg-open
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  %1: ../DocService/node_modules/open/xdg-open
  %2: path-to-executable/xdg-open
> Warning Failed to make bytecode node16-x64 for file /snapshot/server/Common/node_modules/openpgp/dist/openpgp.js
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
> pkg@5.8.1
> Warning Cannot resolve 'name'
  /root/server/Metrics/node_modules/statsd/stats.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve 'name'
  /root/server/Metrics/node_modules/statsd/stats.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
prebuild-install warn install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
delete warning [folder not exist]: /root/build_tools/scripts/../../document-server-integration/web/documentserver-example/nodejs/node_modules
added 211 packages in 1.29s
> pkg@5.8.1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8535  100  8535    0     0   208k      0 --:--:-- --:--:-- --:--:--  208k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 22741  100 22741    0     0  1110k      0 --:--:-- --:--:-- --:--:-- 1168k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16127  100 16127    0     0   828k      0 --:--:-- --:--:-- --:--:--  828k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8535  100  8535    0     0   694k      0 --:--:-- --:--:-- --:--:--  694k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 22741  100 22741    0     0  1388k      0 --:--:-- --:--:-- --:--:-- 1388k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16127  100 16127    0     0  1124k      0 --:--:-- --:--:-- --:--:-- 1124k
Directory not copied
OpenJDK 64-Bit Server VM warning: Insufficient space for shared memory file:
   185431
Try using the -Djava.io.tmpdir= option to select an alternate temp location.

java.io.IOException: No space left on device
        at java.base/java.io.FileOutputStream.writeBytes(Native Method)
        at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
        at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)
        at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:312)
        at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:316)
        at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:153)
        at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:251)
        at java.base/java.io.BufferedWriter.flush(BufferedWriter.java:257)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.closeAppendable(AbstractCommandLineRunner.java:1168)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.outputSingleBinary(AbstractCommandLineRunner.java:1742)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.processResults(AbstractCommandLineRunner.java:1660)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.doRun(AbstractCommandLineRunner.java:1375)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.run(AbstractCommandLineRunner.java:563)
        at com.google.javascript.jscomp.CommandLineRunner.main(CommandLineRunner.java:2279)
Error (java): 254
Error (python): 1
Error (python): 1
Error (./make.py): 1

```

**build_tools base repo version**:

current master

**Operating system**:
ubuntu 16.04 and 20.04

**Comment by adriangibanelbtactic** [comment] 2024-05-07 10:30
No space left on device is quite self-explanatory.

E.g. if your VPS has only a 20 GB sized hard disk try to build it in a VPS with a 100 GB sized hard disk.

**Comment by zhangft7478191** [comment] 2024-05-07 10:31
你的邮件我已收到，谢谢合作！

**Comment by igwyd** [comment] 2024-05-15 10:43
We will close this because the problem is localized, thank you @adriangibanelbtactic.

**Closed** 2024-05-16 09:54 UTC
Labels: fixed
