### ISSUE TITLE
How can I use build_tools in windows?

### ISSUE THREAD

**Issue by sc0rp10n-py** [ONLYOFFICE/build_tools#841] opened 2024-07-17 16:42 UTC
A step guide is missing from the readme. Can anyone help on how to build in Windows?

I just want to use build desktop-apps.

**Comment by igwyd** [comment] 2024-07-31 06:56
Hello @sc0rp10n-py, there are instructions only for Linux, instructions for Windows are still in development. 
Duplicate of #105

**Closed** 2024-07-31 07:13 UTC
